package net.runelite.client.plugins.bestiary.service;

import lombok.extern.slf4j.Slf4j;
import net.runelite.api.Actor;
import net.runelite.api.Client;
import net.runelite.api.GameState;
import net.runelite.api.NPC;
import net.runelite.api.events.ActorDeath;
import net.runelite.api.events.GameStateChanged;
import net.runelite.api.events.HitsplatApplied;
import net.runelite.api.events.InteractingChanged;
import net.runelite.api.events.NpcDespawned;

import javax.inject.Inject;
import javax.inject.Singleton;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

/**
 * Tracks which NPCs the local player is fighting and confirms kills.
 *
 * Primary kill signal:  {@link ActorDeath} \u00e2\u20ac" fires when any actor's health hits 0.
 * Combat tracking:      {@link HitsplatApplied} with {@code hitsplat.isMine()} to identify
 *                       NPCs the local player is actively damaging.
 * Backup tracking:      {@link InteractingChanged} for the initial attack target.
 */
@Slf4j
@Singleton
public class KillTracker {

    private final Client client;

    /**
     * NPCs the local player has dealt damage to, keyed by NPC index.
     * An NPC present here when ActorDeath fires is attributed as a player kill.
     */
    private final Map<Integer, NPC> attackedNpcs = new HashMap<>();

    @Inject
    public KillTracker(Client client) {
        this.client = client;
    }

    /**
     * Tracks NPCs the player damages. {@code isMine()} is true only for hitsplats
     * generated by the local player's attacks.
     */
    public void onHitsplatApplied(HitsplatApplied event) {
        Actor actor = event.getActor();
        if (!(actor instanceof NPC)) {
            return;
        }
        if (!event.getHitsplat().isMine()) {
            return;
        }
        NPC npc = (NPC) actor;
        attackedNpcs.put(npc.getIndex(), npc);
        log.debug("Hitsplat on {} (index {})", npc.getName(), npc.getIndex());
    }

    /**
     * Backup: record the initial interaction target when the player first clicks
     * to attack an NPC (before the first hitsplat lands).
     */
    public void onInteractingChanged(InteractingChanged event) {
        Actor source = event.getSource();
        if (source != client.getLocalPlayer()) {
            return;
        }
        Actor target = event.getTarget();
        if (target instanceof NPC) {
            NPC npc = (NPC) target;
            attackedNpcs.put(npc.getIndex(), npc);
            log.debug("Interacting with {} (index {})", npc.getName(), npc.getIndex());
        }
    }

    /**
     * Primary kill confirmation. Returns the NPC if the local player caused the kill.
     */
    public Optional<NPC> onActorDeath(ActorDeath event) {
        Actor actor = event.getActor();
        if (!(actor instanceof NPC)) {
            return Optional.empty();
        }
        NPC npc = (NPC) actor;
        NPC tracked = attackedNpcs.remove(npc.getIndex());
        if (tracked == null) {
            return Optional.empty();
        }
        log.debug("Kill confirmed via ActorDeath: {} (ID {})", npc.getName(), npc.getId());
        return Optional.of(npc);
    }

    /** Removes a despawned NPC from tracking (cleanup only). */
    public void onNpcDespawned(NpcDespawned event) {
        attackedNpcs.remove(event.getNpc().getIndex());
    }

    /** Clears all state on logout or world hop. */
    public void onGameStateChanged(GameStateChanged event) {
        GameState state = event.getGameState();
        if (state == GameState.LOGIN_SCREEN || state == GameState.HOPPING) {
            attackedNpcs.clear();
        }
    }
}

