package com.bestiary.service;

import lombok.extern.slf4j.Slf4j;
import net.runelite.api.Actor;
import net.runelite.api.Client;
import net.runelite.api.GameState;
import net.runelite.api.NPC;
import net.runelite.api.events.ActorDeath;
import net.runelite.api.events.GameStateChanged;
import net.runelite.api.events.HitsplatApplied;
import net.runelite.api.events.NpcDespawned;

import javax.inject.Inject;
import javax.inject.Singleton;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

/**
 * Tracks which NPCs the local player is fighting and confirms kills.
 *
 * Kill signal:     {@link ActorDeath} fires when any actor's health hits 0.
 * Combat tracking: {@link HitsplatApplied} with {@code hitsplat.isMine()} \u2014 only NPCs the
 *                  local player has dealt at least 1 damage to are eligible for a kill credit.
 *                  InteractingChanged is intentionally NOT used: clicking a monster in
 *                  single combat (0 damage dealt) must not award a kill.
 */
@Slf4j
@Singleton
public class KillTracker {

    private final Client client;

    /**
     * NPCs the local player has dealt damage to, keyed by NPC index.
     * An NPC present here when ActorDeath fires is attributed as a player kill.
     */
    private final Map<Integer, NPC> attackedNpcs = new HashMap<>();

    /** Total damage the local player has dealt to each NPC (by index) — the "observed HP". */
    private final Map<Integer, Integer> damageDealt = new HashMap<>();

    /** Damage the player dealt to the most recently confirmed kill. */
    private int lastKillDamage = 0;
    public int getLastKillDamage() { return lastKillDamage; }

    @Inject
    public KillTracker(Client client) {
        this.client = client;
    }

    /**
     * Tracks NPCs the player damages. {@code isMine()} is true only for hitsplats
     * generated by the local player's attacks.
     */
    public void onHitsplatApplied(HitsplatApplied event) {
        Actor actor = event.getActor();
        if (!(actor instanceof NPC)) {
            return;
        }
        if (!event.getHitsplat().isMine()) {
            return;
        }
        NPC npc = (NPC) actor;
        attackedNpcs.put(npc.getIndex(), npc);
        damageDealt.merge(npc.getIndex(), event.getHitsplat().getAmount(), Integer::sum);
        log.debug("Hitsplat on {} (index {})", npc.getName(), npc.getIndex());
    }

    /**
     * Primary kill confirmation. Returns the NPC if the local player caused the kill.
     */
    public Optional<NPC> onActorDeath(ActorDeath event) {
        Actor actor = event.getActor();
        if (!(actor instanceof NPC)) {
            return Optional.empty();
        }
        NPC npc = (NPC) actor;
        NPC tracked = attackedNpcs.remove(npc.getIndex());
        if (tracked == null) {
            return Optional.empty();
        }
        Integer dmg = damageDealt.remove(npc.getIndex());
        lastKillDamage = dmg != null ? dmg : 0;
        log.debug("Kill confirmed via ActorDeath: {} (ID {}), player damage {}",
                npc.getName(), npc.getId(), lastKillDamage);
        return Optional.of(npc);
    }

    /** Removes a despawned NPC from tracking (cleanup only). */
    public void onNpcDespawned(NpcDespawned event) {
        attackedNpcs.remove(event.getNpc().getIndex());
        damageDealt.remove(event.getNpc().getIndex());
    }

    /** Clears all state on logout or world hop. */
    public void onGameStateChanged(GameStateChanged event) {
        GameState state = event.getGameState();
        if (state == GameState.LOGIN_SCREEN || state == GameState.HOPPING) {
            attackedNpcs.clear();
            damageDealt.clear();
        }
    }
}

